version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: pet_project_web
    command: /start
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file:
      - ./.env/.dev-sample
    depends_on:
      - redis
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=pet_project_db
      - POSTGRES_USER=pet_project_db_admin
      - POSTGRES_PASSWORD=adminpass

  redis:
    image: redis:6-alpine

  celery_worker:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: pet_project_celery_worker
    command: /start-celeryworker
    volumes:
      - .:/code
    env_file:
      - ./.env/.dev-sample
    depends_on:
      - redis
      - db

  celery_beat:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: pet_project_celery_beat
    command: /start-celerybeat
    volumes:
      - .:/code
    env_file:
      - ./.env/.dev-sample
    depends_on:
      - redis
      - db

  flower:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: pet_project_celery_flower
    command: /start-flower
    volumes:
      - .:/code
    env_file:
      - ./.env/.dev-sample
    ports:
      - 5557:5555
    depends_on:
      - redis
      - db

volumes:
  postgres_data:
