version: "3.9"

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=pet_project_db
      - POSTGRES_USER=pet_project_db_admin
      - POSTGRES_PASSWORD=adminpass

volumes:
  postgres_data:
