# Generated by Django 4.0.5 on 2022-07-31 12:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customuser_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='subscribers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
