# Generated by Django 4.0.5 on 2022-07-28 12:49

from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_additionalimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='main_image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.mainimage'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(default='default.jpg', upload_to='images/', verbose_name='Image'),
        ),
    ]
