# Generated by Django 4.0.5 on 2022-07-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_main_image_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='additional_images',
            field=models.ManyToManyField(to='blog.additionalimage'),
        ),
    ]
