# Generated by Django 4.0.5 on 2022-07-29 06:03

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_additionalimage_image_ppoi_mainimage_image_ppoi'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='additionalimage',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(upload_to='media/images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='mainimage',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(upload_to='media/images/', verbose_name='Image'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
