# Generated by Django 4.0.5 on 2022-07-29 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_published_alter_additionalimage_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='published',
            new_name='blocked',
        ),
    ]
