# Generated by Django 4.0.5 on 2022-08-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
