# Generated by Django 4.0.5 on 2022-08-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_post_additional_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='additional_images',
            field=models.ManyToManyField(blank=True, null=True, to='blog.additionalimage'),
        ),
    ]
