# Generated by Django 4.0.5 on 2022-08-11 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_additionalimage_mainimage_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainimage',
            name='post',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_image', to='blog.post'),
        ),
    ]
