# Generated by Django 4.0.5 on 2022-08-11 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_mainimage_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalimage',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_image', to='blog.post'),
        ),
    ]
