# Generated by Django 4.0.5 on 2022-08-12 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_alter_mainimage_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainimage',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='main_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_image', to='blog.mainimage'),
        ),
    ]
