# Generated by Django 4.0.5 on 2022-09-12 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_post_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
